// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("MvcMovie.Models.Person", b =>
                {
                    b.Property<string>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });
             modelBuilder.Entity("MvcMovie.Models.DaiLy", d =>
                {
                    d.Property<string>("MaDaiLy")
                        .HasColumnType("TEXT");

                    d.Property<string>("TenDaiLy")
                        .HasColumnType("TEXT");

                    d.Property<string>("DiaChi")
                        .HasColumnType("TEXT");

                    d.Property<string>("NguoiDaiDien")
                        .HasColumnType("TEXT");

                    d.Property<string>("DienThoai")
                        .HasColumnType("TEXT");

                    d.Property<string>("MaHTPP")
                        .HasColumnType("TEXT");

                    d.HasKey("MaDaiLy");

                    d.ToTable("DaiLy");
                });    
#pragma warning restore 612, 618
        }
    }
}
